config/routes.rb
Rails.application.routes.draw do
  root 'apis#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :apis, only: [:index, :show, :new, 
                          :create, :edit, :update, :destroy] do

    resources :reviews, only: [:index, :new, 
                               :create, :edit, :update, :destroy] do
      member do
        post 'upvote'
        post 'downvote'
      end
    end
  end
  resources :users, only: [:index, :show, :destroy]
end

app/models/api.rb
class Api < ActiveRecord::Base
  belongs_to :user
  has_many   :reviews, dependent: :destroy

  validates :name, presence: true
  validates :url, presence: true
  validates :name, uniqueness: { scope: :url }
  validates :description, presence: true

  CATEGORIES = [
    'News',
    'Sports',
    'Data',
    'Events',
    'Food',
    'Music',
    'Financial',
    'Geolocation'
  ]

  def self.add_tags(api, tags)
    tags.each do |tag|
      new_tag = Tag.new(name: "#{tag}")
      new_tag.save
      new_join = ApiTag.new(api: api, tag: new_tag)
      new_join.save
    end
  end

  def owner?(user)
    if self.user == user
      true
    else
      false
    end
  end

  def average_rating
    total_score = 0
    total_reviews = self.reviews.count

    rating = self.reviews.each do |review|
      total_score += review.rating
    end

    unless total_reviews == 0
      total_score / total_reviews
    else
      0 
    end
  end

  def print_stars(average_rating)
    stars = ''
    unless average_rating == 0 
      average_rating.times do
        stars += '★ '
      end
      (5-average_rating).times do
        stars += '☆ '
      end
    else
      stars = '☆ ☆ ☆ ☆ ☆'
    end
    stars
  end

  def self.search(query)
    results = Api.where("name LIKE ? OR description LIKE ? OR url LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :api
  has_many   :votes, dependent: :destroy

  validates :body, presence: true
  validates :rating, inclusion: {in: [1, 2, 3, 4, 5]}
  validates :user_id, presence: true
  validates :api_id, presence: true

  def review_owner?(user)
    if self.user == user
      true
    else
      false
    end
  end

  def calculate_votes(review_id)
    upvotes   = Vote.where(up_vote?: true,  review: review_id).count
    downvotes = Vote.where(up_vote?: false, review: review_id).count
    { score: upvotes - downvotes, total: upvotes + downvotes }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  devise :database_authenticatable, :registerable, 
    :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :review
  belongs_to :user

  def create(review_id, user_id, up_or_down)
    Votes.create(
      user: User.find(user_id),
      review: Review.find(review_id),
      user_vote: up_or_down)
  end

  def flip_vote(vote)
    if vote.user_vote
      vote.user_vote = false
    else
      vote.user_vote = true
    end
    vote.save
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
    end
  end
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index, :random, :about]

  def index
    if params[:search]
      @apis  = Api.search(params[:search])
      @title = 'Search Results'
    elsif params[:cat] != nil
      @apis  = Api.where(category: params[:cat])
      @title = params[:cat]
    else
      trending_reviews = Review.all.sort_by{|r| r.created_at}.reverse.first(20)
      trending_apis    = []
      trending_reviews.each do |review|
        trending_apis << review.api
      end
      @apis  = trending_apis 
      @title = 'Trending'
    end
  end

  def show
    @api     = Api.find(params[:id])
    @review  = Review.new
    @reviews = @api.reviews.sort_by{ |r| r.votes.count }.reverse!
  end

  def edit
    @api = Api.find(params[:id])
  end

  def new
    @api = Api.new
  end

  def create
    params[:api][:tags] = params[:api][:tags].split(',')
    api = Api.new(api_params)
    api.user = current_user
    if api.save
      Api.add_tags(api, params[:api][:tags])
      flash[:success] = 'New API Created!'
      redirect_to api_path(api)
    else
      flash[:failure] = api.errors.full_messages.join(', ')
      flash[:failure] += '. API Not Created.'
      render :new
    end
  end

  def update
    params[:api][:tags] = params[:api][:tags].split(',')
    @api = Api.find(params[:id])
    if @api.update(api_params)
      redirect_to api_path(@api)
      flash[:success] = 'Api Updated!'
    else
      flash[:failure] = 'Api Not Updated!'
      render :edit
    end
  end

  def destroy
    @api = Api.find(params[:id])
    @reviews = @api.reviews
    if @api.destroy
      @reviews.destroy
      flash[:success] = 'API Deleted'
      redirect_to apis_path
    end
  end

  def about
    render :about
  end

  private

  def api_params
    params.require(:api).permit(
      :name, :url, :description, :paid, :tags, :category)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(
      :first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]

  def index
    @reviews = Reviews.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def upvote
    api    = params[:api_id]
    review = params[:id]
    user   = current_user.id
    Vote.create(api_id: api, user_id: user, review_id: review, up_vote?: true) 
    redirect_to(api_path(api))
  end

  def downvote
    api    = params[:api_id]
    review = params[:id]
    user   = current_user.id
    Vote.create(api_id: api, user_id: user, review_id: review, up_vote?: false) 
    redirect_to(api_path(api))
  end

  def create
    @api = Api.find(params[:api_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.api_id = @api.id

    if @review.save
      flash[:success] = 'Review Submitted Successfully!'
    else
      flash[:warning] = @review.errors.full_messages.join(', ')
      flash[:warning] += 'Review Submission Failure'
    end
    redirect_to api_path(@api)
  end

  def edit
    @api = Api.find(params[:api_id])
    @review = Review.find(params[:id])
    if @review.save
      # ReviewMailer.new_review(@review).deliver_later
      flash[:success] = 'Review Updated Successfully!'
    else
      flash[:warning] = @review.errors.full_messages.join(', ')
      flash[:warning] += 'Review Update Failed'
    end
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to apis_path
      flash[:success] = "Review Updated!"
    else
      flash[:failure] = "Review Not Updated!"
      render :edit
    end
  end

  def destroy
    @api = Api.find(params[:api_id])
    @review = Review.find(params[:id])
    if @review.destroy
      flash[:success] = "Review has been deleted"
      redirect_to apis_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:body, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, except: :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, alert: 'Access denied.'
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, notice: 'User updated.'
    else
      redirect_to users_path, alert: 'Unable to update user.'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, alert: 'Access denied.'
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end
end

app/views/apis/_new_review.html.erb
<h4>Review This API</h4>

<%= form_for [@api, @review] do |f| %>

  <%= f.text_area :body, rows: 8, value: @review.body %>
  <%= f.label :rating %>
  <%= f.collection_radio_buttons(:rating, 
                                 [[1], [2], [3], [4], [5]], :first, :last) %>
  <%= f.submit "Add Review" %>

<% end %>

app/views/apis/edit.html.erb
<h1>Edit API</h1>

<%= form_for @api do |f| %>
  <%= f.text_field :name, id: "Name", value: @api.name %>
  <%= f.text_field :url, id: "URL", value: @api.url %>
  <%= f.text_field :description, id: "Description", value: @api.description  %>
  <%= f.text_field :tags, value: "", id: "Tags" %>
  Paid?
  <%= f.collection_radio_buttons(:paid, [[true, "Yes."], [false, "No."]], 
    :first, :last) %>
  <%= f.submit "Update API" %>
<% end %>

<%= link_to 'Back', apis_path %>

app/views/apis/index.html.erb
<% require 'will_paginate/array' %>

<div class="index-container">
    <div class="index-title">
      <%= @title %>
    </div>
  <% @apis_paginated = @apis.paginate(page: params[:page], per_page: 5) %>
  <% @apis_paginated.each do |api| %>
    <div class="api-frame">
      <div class="trending-api">
        <div class="trending-api-info">
          <div style="font-weight: 700;">
            <%= link_to(api.name, api_path(api)) %> <br />
          </div>
          <div style="font-weight: 400;">
            <%= link_to(api.url, api.url) %>
          </div>
          <span style="font-weight: 700;">Category:</span> <%= api.category %>
      </div>
      <div class="trending-api-rating">
        <div class="rating-fill"></div>
        <div class="rating">
          <div class="rating-stars">
            <% unless api.average_rating == 0 %>
              <%= api.print_stars(api.average_rating) %>
          </div>
          <div class="rating-score">
            <%= "#{api.average_rating} Star Average" %>
          <% else %>
            <%= 'No Reviews' %>
          <% end %>
          </div>
        </div>
      </div>
      <div class="trending-api-review-button">
        <div class="review-button-fill"></div>
        Review
      </div>
      </div>
    </div>
  <% end %>

  <div class="pagination-centered pagination-links">
    <%= will_paginate @apis_paginated,
      page_links: false,
      next_label:     image_tag('arrow_next.png', size: '50'),
      previous_label: image_tag('arrow_back.png', size: '50') %>
  </div>
</div>

app/views/apis/new.html.erb
<div class="new_api_title">
  Share An API 
</div>

<div class="medium-8 medium-centered columns">
  <%= form_for Api.new do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, id: 'Name' %>
    <%= f.label :link %>
    <%= f.text_field :url, id: 'URL' %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :category %>
    <%= f.select :category, options_for_select(Api::CATEGORIES) %>
    <%= f.label :free, 'Free to Use?'%>
    <%= f.collection_radio_buttons(:free, [[true, 'Yes'], [false, 'No']], 
                                   :first, :last) %> <br />
    <div class="centered" style="margin-top: 10px;">
      <%= f.submit 'Add API', class: 'button' %>
    </div>
  <% end %>
</div>

app/views/apis/show.html.erb
<div class="page_content">

  <div class="api_info">
    <% if @api.owner?(current_user) || current_user.try(:admin?) %>
      <%= link_to 'Edit API', edit_api_path(@api), 
        class: 'small button' %> <br />
        <%= link_to 'Delete API', @api, method: :delete, 
          class: 'small button', 
          data: { confirm: 'Are You Sure You Want to Delete this API?' } %>
    <% end %>

    <div class="posted_by">
      <%= "Posted by #{@api.user.first_name} 
      on #{@api.created_at.strftime("%m-%d-%Y")}" %>
    </div>

    <h4>
      API: <span class="title"><%= @api.name %></span> <br />
      LINK: <span class="link"><%= link_to @api.url, @api.url %></span> <br />
      CATEGORY: <b><%= @api.category %></b>
    </h4>

    <div class="api_description">
      <%= @api.description %>
    </div>
  </div>

  <div class="review">
    <h3>Review Now</h3>

    <%= form_for [@api, @review] do |f| %>
      <%= f.collection_radio_buttons(:rating, [[1], [2], [3], [4], [5]], 
                                     :first, :last) %>
      <%= f.text_area :body, rows: 8, value: @review.body %>
      <%= f.submit 'Post Review', class: 'submit_button_dark' %>
    <% end %>

    <h2>Reviews</h2>
    <% @reviews.each do |review|%>
      <div class="review_container">
        <% upvote_path   = upvote_api_review_path(@api, review).to_s %> 
        <% downvote_path = downvote_api_review_path(@api, review).to_s %>
        <% vote_score    = review.calculate_votes(review.id) %>

        <div class="review_body">
        <div class="upvote_frame">
          <div class="upvote_body">
            <div class="upvote">
              <a id="up_vote" class="upvote" 
                              data-path="<%= upvote_path %>"></a>
              <span class="count"><%= vote_score[:score] %></span>
              <a id="down_vote" class="downvote" 
                                data-path="<%= downvote_path %>"></a>
              <div class="score">
                <%= vote_score[:total] %><br \>Total
              </div>
            </div>
          </div>
        </div>
          <div class="review_content">
          <div class="review_crud_buttons">
            <% if review.review_owner?(current_user) || 
                 current_user.try(:admin?) %>
               <%= link_to 'Edit Review', edit_api_review_path(@api, review), 
                 class: 'review_crud_button' %> 
              <%= link_to 'Delete Review', api_review_path(@api, review),
                class: 'review_crud_button', method: :delete, 
                data: {confirm: 'Are You Sure You Want to Delete this Review?'} %>
            <% end %>
          <h5>
            <%= "#{review.user.first_name} Says" %>
          </h5>
          <p>
            <b>Rating:</b> <%= review.rating %> <br />
            <b>Reason:</b> <%= review.body %>
          </p>
        </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'votes' %>
<%= javascript_include_tag 'jquery-upvote' %>

app/views/application/_new_review_form.html.erb
<div class="body-background">
  <div class="medium-centered api-review detail-text-medium float-center">
    <h4>Review This API</h4>
    <%= form_for [@api, @review] do |f| %>
      <div class="row">
        <%= f.text_area :body, rows: 8, value: @review.body %>

        <%= f.label :rating %>
        <%= f.collection_radio_buttons(:rating,
                                       [[1], [2], [3], [4], [5]], 
                                       :first, :last) %>
    </div>

    <div class="row">
      <%= f.submit "Add Review" %>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round 
      <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, 
    method: 'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" role="navigation" >
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
  </ul>
  <section class="top-bar-section">
      <%= render 'layouts/navigation_links' %>
  </section>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="left">
  <li class="has-dropdown">
    <a href="#">Menu</a>
    <ul class="dropdown">
      <li><%= link_to 'Add An API', new_api_path %></li>
      <li><%= link_to 'Show Random', api_path(Api.all.sample) %></li>
      <li><%= link_to 'About Us', page_path('about') %></li>
    </ul>

    <li class="has-dropdown">
      <a href="#">Categories</a>
      <ul class="dropdown">
        <% Api::CATEGORIES.each do |category| %>
          <li><%= link_to "#{category}", apis_path(cat: "#{category}")%></li>
        <% end %>
      </ul>
    </li>

    <li class="has-form">
      <div class="row collapse">
        <div class="large-8 small-9 columns" >
          <%= form_tag(apis_path, method: 'get', id: 'search-form') do %>
            <%= text_field_tag :search, params[:search],
              placeholder: 'Search', id: 'search-field' %>
      </div>

      <div class="large-4 small-3 columns" >
        <%= submit_tag 'Search', class: 'alert button expand' %>
      </div>
    <% end %> 
    </div>
  </li>
</ul>

app/views/layouts/_topper.html.erb
<div class="topper left-section">
	<%= image_tag('Logo_Small') %>
	<%= link_to 'API-Addicts', apis_path, style: 'color: #0076b3;' %>
</div>
<div class="right-section">
	<% if user_signed_in? %>
		<div class="right-section-button" style="background-color: #5799b1;">
			<%= link_to 'Log Out', destroy_user_session_path, method: 'delete' %>
		</div>
	<% else %>
		<div class="right-section-button" style="background-color: #757575;">
			<%= link_to 'Sign Up', new_user_registration_path %>
		</div>
		<div class="right-section-button" style="background-color: #5799b1;">
			<%= link_to 'Log In', new_user_session_path %>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,900,100'
      rel='stylesheet' type='text/css'>
    <title><%= content_for?(:title) ? yield(:title) : 'API-Addicts' %></title>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'votes' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="topper">
      <%= render 'layouts/topper' %>
    </div>

    <nav class="top-bar" data-topbar>
      <div class="top-bar-section">
        <ul>
          <%= render 'layouts/navigation_links' %>
        </ul>
      </div>
    </nav>

    <% unless flash.keys[0] == nil %>
      <div data-alert class="alert-box">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "flash #{key}") %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="page_content">
  <h2>About Us</h2>

  <div class="about_api_description">
    There's one force factor that's driving web innovation above all others today: APIs. We're addicted to them, and our users are too!<br /><br />
    Our service allows users to create an account, post new APIs to share, then gives other users the opportunitiy to rate, review, and upvote them.<br>
  </div>
  
  <h3>Features</h3>
    <ul>
      <li>User signs up</li>
      <li>User uploads a profile picture</li>
      <li>User adds an API</li>
      <li>User reviews existing API</li>
      <li>User upvotes or downvotes API (user can only vote once)</li>
      <li>API creater recieves email when someone reviews their</li>
      <li>Admin deletes content they deem innapopropriate</li>
      <li>Admin deletes user account if they violate terms of use</li>
    </ul>
  
  <h3>Technologies Utilized</h3>
    <ul>
      <li> Rails</li>
      <li>Ajax</li>
      <li>JQuery</li>
      <li>Devise (User Authentication)</li>
      <li>CarrierWave (Photo Uploads)</li>
      <li>Will_Paginate (Pagination)</li>
      <li>Amazon S3 Service</li>
      <li>Factory_Girl (Test Data)</li>
      <li>Mailgun (ActionMailer)</li>
    </ul>

  <h3>Development Team</h3>
    <ul>
      <li>Matt Thompson</li>
      <li>Brett Mordas</li>
      <li>Majid Ihsan</li>
      <li>Eric Fournier</li>
    </ul>
</div>

app/views/reviews/edit.html.erb
<%= form_for [@api, @review] do |f| %>
  <div class="row">
    <%= f.text_area :body, value: @review.body  %>

    <%= f.label :rating %>
    <%= f.collection_radio_buttons(:rating,
      [[1], [2], [3], [4], [5]], :first, :last) %>
  </div>

  <div class="row">
    <%= f.submit "Update Review" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', class: 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to('Delete user', user_path(user), 
    data: { confirm: 'Are you sure?' }, 
    method: :delete, class: 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>